### ISSUE TITLE
No battery information for ASUS laptop

### ISSUE THREAD

**Issue by PanderMusubi** [lpereira/hardinfo#24]
On ASUS laptop UX31A, no battery information is displayed. Only the message "No batteries found on this system" is reported and on the command line

```
sh: 0: -c requires an argument
```

is printed. This concerns HardInfo version 0.5.1 on Ubuntu 15.10 Wily.

**Comment by mckaygerhard** [comment]
i start hardinfo and could reproduce u'r bug.. also the hardinfo of venenux its now 0.5.2pre so i think the query to consult the battery was change..

can u try with lasted?

and in any cae in my 0.5.2pre i cannot get some battery info... i'll try later to revise the code.. for now i cannot due i'm now very busy at my job

**Comment by PanderMusubi** [comment]
Do you have a PPA with a build of the latest for Ubuntu Wily?

**Comment by lpereira** [comment]
There are no official PPAs for HardInfo. It's possible that you'll find people that maintain them unofficially, though.

**Comment by mckaygerhard** [comment]
@PanderMusubi since winbuntu 13 or 14, respect debian wheeze, multiarch was implemented, so path changed! my packages does not work for you.

BUT: hardinfo package already has recent build on each distro, so i think u'r problem are other

please try to send a bug request for to package mantainer firts, then here..

currently in my system i cannot get any info from battery if the machine are no laptop..
i not try in the laptop.. i post feedback later ... but the error in command line you cited a never got it!

**Comment by lpereira** [comment]
This should be working now in HEAD. Just tested on a machine with kernel 4.3.3, with two batteries, and things are displayed as they should. Do you need help building HardInfo from source?

**Comment by mckaygerhard** [comment]
this are working please no feedback from author of issue so close this!

**Comment by PanderMusubi** [comment]
Ubuntu still ships version 0.5.1 in the last eight releases, that is the last four years. Perhaps put up a new release for testing (in a PPA or another way) and upgrade the version shipped in Ubuntu.

**Comment by mckaygerhard** [comment]
u can take it a debian source package and build yourselft a deb for winbuntu from venenux repository

**Comment by PanderMusubi** [comment]
Thanks, but I will wait for upgrades to appear on Ubuntu.

**Comment by mckaygerhard** [comment]
this issue was solved some time ago, please close it!

**Comment by PanderMusubi** [comment]
As it is still an issue for Ubuntu with 0.5.1-1.4ubuntu3, could you please tell me from which version onwards this is fixed? Thanks

**Comment by mckaygerhard** [comment]
hi @PanderMusubi in lasted conversation i cited that recent commit fixeds that but u said "wait for winbuntu updates" .. i tell u that those updates seems not comming for now.. package at winbuntu are orphaned, 

so u can take the debian sources at venenux repository and rec ompiles easy that will generate a package, or try compile at hand from here that some commiter nade recent and good changes

**Comment by PanderMusubi** [comment]
I will try to get Ubuntu to pick this up, one way or the other. With a version bump, this goes usually quicker. Thanks for the info.

See also https://launchpad.net/ubuntu/+source/hardinfo and https://bugs.launchpad.net/ubuntu/+source/hardinfo/+bug/1308853

**Comment by mckaygerhard** [comment]
for those that not known: orphaned meas no one are updating the packaged. no nwer version of winbuntu will get that.. until a package mantainer take the responsability of the package and retreive a newer version in debian.. so winbuntu will get a newer version, the normal workflow are that if debian have a newer so will have winbuntu.. in some exception the winbutnu are the main source of the package between the debian based distributions... in the main bugtraker i'll try to made some debian changes but the mantainer and mentors process are too complicated and tedius
